version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for GitHub Actions
  # NOTE(ekilmer): Disabled because dependabot needs access to GHA secrets and
  # the submodule updates aren't super critical right now
  # - package-ecosystem: "gitsubmodule"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
