cache:
  timeout: 660
  pip: true
  custom_install: true
  directories:
    - sources

matrix:
  include:
    - os: osx
      language: generic

before_install:
  - ./travis.sh "$TRAVIS_OS_NAME" initialize

install: true
script:
  - ./travis.sh "$TRAVIS_OS_NAME" build
