name: CI

on:
  push:
    branches:
      - master
      - gh-mac
  pull_request:
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron:  '0 6 * * *'

jobs:
  tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Run Tests
      run: |
        ./travis.sh osx initialize
        ./travis.sh osx build
