name: Docker Build Images

on:
  schedule:
    # Once every Wednesday at 00:00
    - cron: '0 0 * * 3'
  push:
    # branches:
    #   - master
    paths:
      - 'docker/**'
      - '.github/workflows/vcpkg_docker.yml'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        container:
          - { distro: 'ubuntu', version: '18.04' }
          - { distro: 'ubuntu', version: '20.04' }

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.0.3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: publisher
          password: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.2.1
        with:
          file: ./docker/Dockerfile.${{ matrix.container.distro }}.vcpkg
          target: caching
          context: ./docker
          push: true
          tags: docker.pkg.github.com/${{ github.repository_owner }}/vcpkg-builder-${{ matrix.container.distro }}:${{ matrix.container.version }}
          build-args: DISTRO_VERSION=${{ matrix.container.version }}
